### ISSUE TITLE
Model not found error on bot test

### ISSUE THREAD

**Issue by haganbt** [hunkim/Wit-Facebook#10]
When running the bot test:

```
WIT_TOKEN=xxx node bot
```

I get:

```
Bot testing mode.
> what is the weather?
[error] [converse] Error: Model not found (404)
[error] Model not found (404)
```

Any ideas?

**Comment by haganbt** [comment]
Apologies, RTFM. Needed to create a story.

**Comment by lamkent00** [comment]
Hi everyone,
I'm try to running messenger.js and get error: 
`[wit] [converse] Error: Model not found (404)`
Google tell me must create a story for bot. 
But it was solusion in 2016. For now, WIT notification Stories and POST /converse have been deprecated. This will break in February 2018!
==> So, anyone can help me to pass it plz ? any solusion for this problem in 2017 ?
