### ISSUE TITLE
Does not seem to work anymore

### ISSUE THREAD

**Issue by sdeff** [hunkim/Wit-Facebook#5]
Hi,

I've set up a messenger bot on Heroku which worked fine. But since a few days it doesn't respond to any messages even though I didn't change a thing.

**Comment by hunkim** [comment]
Did you check again? Did you get any error message?

**Comment by hunkim** [comment]
@sdeff I tested it again, but it seems OK. Let me know if you get some errors.

**Comment by ag** [comment]
@hunkim @sdeff same here
